-- ---------------------------------------------------------------------------
-- V1: core schema for RentalHub
-- Flyway runs this once, in order, and records it in a flyway_schema_history
-- table so it never runs twice. Never edit a migration that has been committed;
-- add a new V2, V3, ... instead.
-- ---------------------------------------------------------------------------

-- vector      : pgvector, used later for AI listing embeddings
-- btree_gist  : lets an exclusion constraint mix "=" on a bigint with "&&" on a range
CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS btree_gist;


CREATE TABLE users (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name   VARCHAR(120) NOT NULL,
    email       VARCHAR(200) NOT NULL UNIQUE,
    role        VARCHAR(20)  NOT NULL,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
);


-- Single-table inheritance: Apartment / Villa / Cabin / Studio all live here.
-- 'property_type' is the discriminator column that tells Hibernate which Java
-- class to build. Subtype-specific columns are nullable because they only
-- apply to one subtype; the per-type rules live in the factory's creators.
CREATE TABLE properties (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_type       VARCHAR(31)  NOT NULL,
    host_id             BIGINT       NOT NULL REFERENCES users (id),

    title               VARCHAR(150) NOT NULL,
    description         TEXT         NOT NULL,
    city                VARCHAR(100) NOT NULL,
    country             VARCHAR(100) NOT NULL,
    address             VARCHAR(255),

    -- NUMERIC, never float/double. Exact decimal arithmetic, no rounding drift.
    price_per_night     NUMERIC(19, 4) NOT NULL CHECK (price_per_night > 0),
    currency            VARCHAR(3)     NOT NULL,

    max_guests          INT          NOT NULL CHECK (max_guests > 0),
    bedrooms            INT          NOT NULL DEFAULT 0 CHECK (bedrooms >= 0),
    bathrooms           INT          NOT NULL DEFAULT 0 CHECK (bathrooms >= 0),

    active              BOOLEAN      NOT NULL DEFAULT TRUE,
    available_until     DATE,

    created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),

    -- Optimistic locking counter. Hibernate bumps this on every write and
    -- refuses the write if someone else bumped it first.
    version             BIGINT       NOT NULL DEFAULT 0,

    -- Apartment
    floor_number        INT,
    has_elevator        BOOLEAN,
    -- Villa
    has_pool            BOOLEAN,
    plot_area_sqm       NUMERIC(10, 2),
    -- Cabin
    heating_type        VARCHAR(30),
    distance_to_town_km NUMERIC(6, 2),
    -- Studio
    has_sofa_bed        BOOLEAN,
    area_sqm            NUMERIC(10, 2)
);

-- lower(city) matches the search query's LOWER(p.city) = LOWER(:city), so the
-- case-insensitive city filter can use an index instead of scanning every row.
CREATE INDEX idx_properties_city   ON properties (lower(city));
CREATE INDEX idx_properties_active ON properties (active);
CREATE INDEX idx_properties_price  ON properties (price_per_night);
CREATE INDEX idx_properties_host   ON properties (host_id);


CREATE TABLE property_images (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_id BIGINT       NOT NULL REFERENCES properties (id) ON DELETE CASCADE,
    url         VARCHAR(500) NOT NULL,
    s3_key      VARCHAR(500),
    sort_order  INT          NOT NULL DEFAULT 0,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX idx_property_images_property ON property_images (property_id);


CREATE TABLE bookings (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_id       BIGINT       NOT NULL REFERENCES properties (id),
    guest_id          BIGINT       NOT NULL REFERENCES users (id),

    check_in          DATE         NOT NULL,
    check_out         DATE         NOT NULL,
    guests            INT          NOT NULL CHECK (guests > 0),

    -- Always the amount actually charged, in the property's own currency.
    -- Converted display values are computed on the fly and never stored.
    total_amount      NUMERIC(19, 4) NOT NULL CHECK (total_amount > 0),
    currency          VARCHAR(3)     NOT NULL,

    -- Checked against an explicit list because the exclusion constraint below
    -- matches on these exact strings: a misspelt status would silently escape it.
    status            VARCHAR(20)  NOT NULL
        CHECK (status IN ('PENDING', 'CONFIRMED', 'CANCELLED', 'COMPLETED')),
    payment_reference VARCHAR(120),

    created_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version           BIGINT       NOT NULL DEFAULT 0,

    CONSTRAINT chk_booking_dates CHECK (check_out > check_in)
);

CREATE INDEX idx_bookings_property ON bookings (property_id);
CREATE INDEX idx_bookings_guest    ON bookings (guest_id);

-- The database-level guarantee against double booking.
-- Two live bookings for the same property may not have overlapping date ranges.
-- '[)' = check-in inclusive, check-out exclusive, so one guest can check out on
-- the same day the next guest checks in.
ALTER TABLE bookings
    ADD CONSTRAINT no_overlapping_bookings
        EXCLUDE USING gist (
            property_id WITH =,
            daterange(check_in, check_out, '[)') WITH &&
        ) WHERE (status IN ('PENDING', 'CONFIRMED'));


CREATE TABLE reviews (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_id BIGINT      NOT NULL REFERENCES properties (id) ON DELETE CASCADE,
    author_id   BIGINT      NOT NULL REFERENCES users (id),
    rating      INT         NOT NULL CHECK (rating BETWEEN 1 AND 5),
    comment     TEXT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_reviews_property ON reviews (property_id);
CREATE INDEX idx_reviews_author   ON reviews (author_id);


CREATE TABLE favorites (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    property_id BIGINT      NOT NULL REFERENCES properties (id) ON DELETE CASCADE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    -- The unique constraint's index starts with user_id, so it already serves
    -- lookups by user; property_id needs its own index.
    CONSTRAINT uq_favorite UNIQUE (user_id, property_id)
);

CREATE INDEX idx_favorites_property ON favorites (property_id);
