-- ---------------------------------------------------------------------------
-- V2: auditing (Hibernate Envers), and one review per guest per listing
--
-- Envers writes the history; Flyway creates its tables, because Hibernate only
-- validates the schema (ddl-auto: validate). Column names and types match what
-- Hibernate expects for the @Audited entities; startup fails if they drift.
-- ---------------------------------------------------------------------------

-- One row per audited transaction (a "revision"): when it happened and who did it.
CREATE TABLE revinfo (
    rev         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    revtstmp    BIGINT       NOT NULL,   -- milliseconds since 1970-01-01 UTC
    changed_by  VARCHAR(100) NOT NULL    -- user:<id>, system:<job> or anonymous
);


-- History tables: each audited row as it was after each revision, plus
--   rev      which revision (and so when, and by whom)
--   revtype  0 = created, 1 = updated, 2 = deleted
--
-- Deliberately permissive: no NOT NULL on business columns, no CHECK lists, and no
-- foreign keys to the live tables, because history outlives the rows it describes
-- (a deleted listing's history must still be readable) and must be able to record
-- values that later rules would forbid. The one foreign key is to revinfo.

CREATE TABLE properties_aud (
    id                  BIGINT       NOT NULL,
    rev                 BIGINT       NOT NULL REFERENCES revinfo (rev),
    revtype             SMALLINT,
    property_type       VARCHAR(31)  NOT NULL,
    host_id             BIGINT,
    title               VARCHAR(150),
    description         TEXT,
    city                VARCHAR(100),
    country             VARCHAR(100),
    address             VARCHAR(255),
    price_per_night     NUMERIC(19, 4),
    currency            VARCHAR(3),
    max_guests          INT,
    bedrooms            INT,
    bathrooms           INT,
    active              BOOLEAN,
    available_until     DATE,
    created_at          TIMESTAMPTZ,
    -- Apartment
    floor_number        INT,
    has_elevator        BOOLEAN,
    -- Villa
    has_pool            BOOLEAN,
    plot_area_sqm       NUMERIC(10, 2),
    -- Cabin
    heating_type        VARCHAR(30),
    distance_to_town_km NUMERIC(6, 2),
    -- Studio
    has_sofa_bed        BOOLEAN,
    area_sqm            NUMERIC(10, 2),
    PRIMARY KEY (id, rev)
);

CREATE TABLE bookings_aud (
    id                BIGINT NOT NULL,
    rev               BIGINT NOT NULL REFERENCES revinfo (rev),
    revtype           SMALLINT,
    property_id       BIGINT,
    guest_id          BIGINT,
    check_in          DATE,
    check_out         DATE,
    guests            INT,
    total_amount      NUMERIC(19, 4),
    currency          VARCHAR(3),
    status            VARCHAR(20),
    payment_reference VARCHAR(120),
    created_at        TIMESTAMPTZ,
    PRIMARY KEY (id, rev)
);

CREATE TABLE reviews_aud (
    id          BIGINT NOT NULL,
    rev         BIGINT NOT NULL REFERENCES revinfo (rev),
    revtype     SMALLINT,
    property_id BIGINT,
    author_id   BIGINT,
    rating      INT,
    comment     TEXT,
    created_at  TIMESTAMPTZ,
    PRIMARY KEY (id, rev)
);

-- The primary keys serve "the history of row X". These serve "everything revision N
-- changed", and keep the foreign keys to revinfo cheap to check.
CREATE INDEX idx_properties_aud_rev ON properties_aud (rev);
CREATE INDEX idx_bookings_aud_rev   ON bookings_aud (rev);
CREATE INDEX idx_reviews_aud_rev    ON reviews_aud (rev);


-- A guest reviews a listing once (and can edit that review). ReviewService checks
-- first, for a friendly message; this makes it true even for two requests at once.
-- Its index starts with property_id, so it also serves "a listing's reviews", and
-- the V1 index on property_id alone is no longer needed.
ALTER TABLE reviews ADD CONSTRAINT uq_review_author_property UNIQUE (property_id, author_id);
DROP INDEX idx_reviews_property;
